[package]
name = "flair_core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
convert_case = "0.5.0"
log = "0.4.17"
log4rs = "1.1.1"