[package]
name = "flair_core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
convert_case = "0.5.0"
syn = "1.0"
quote = "1.0"
proc-macro2 = { version = "1.0.9", default-features = false }
log = "0.4.17"
log4rs = "1.1.1"
tokio = { version = "1.6", features = ["rt-multi-thread", "time", "macros", "signal", "process"] }
sqlx = { version = "0.6.1", default-features = false, features = ["runtime-tokio-native-tls", "mysql", "chrono", "bigdecimal", "macros"] }
